### ISSUE TITLE
Please add a license file

### ISSUE THREAD

**Issue by unixorn** [ecmma/shelf#1]
I'd like to add this to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins), but it doesn't have a license file.

Please add a license file - if you don't have one in mind,  I recommend using [choosealicense.com](https://choosealicense.com) to help choose an appropriate one.

Thanks!

**Comment by ecmma** [comment]
Commit [2126269](https://github.com/ecmma/shelf/commit/2126269c0dbe1ac4715b24ea758784205e7f06b0) adds GNU GPLv3 license to the project. 

Thanks for the interest!
